name: Build/Release MBCord

on:
  push:
    branches: [ master ]
    paths:
      - 'package.json'
  pull_request:
    branches: [ master ]
    paths:
      - 'package.json'
  workflow_dispatch:


env:
  GH_TOKEN: ${{ secrets.github_token }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean install NPM
        run: npm clean-install

      - name: Build/Release Electron app
        run: npm run release
        
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v3
        with: 
          path: |
            dist/*.exe
            dist/*.appImage
            dist/*.deb
            dist/*.dmg
            
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: palette.flatpak
        manifest-path: org.gnome.zbrown.Palette.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Upload Artifacts 
      uses: actions/upload-artifact@v3
       
  
      
