name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: SandwichFox.mbcord
          installers-regex: '\.exe$' # Only .exe files
          delete-previous-version: 'true' # don't forget to quotes
          token: ${{ secrets.WINGET_TOKEN }}
